// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerEndpoint) DeepCopyInto(out *PeerEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerEndpoint.
func (in *PeerEndpoint) DeepCopy() *PeerEndpoint {
	if in == nil {
		return nil
	}
	out := new(PeerEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerPort) DeepCopyInto(out *PeerPort) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerPort.
func (in *PeerPort) DeepCopy() *PeerPort {
	if in == nil {
		return nil
	}
	out := new(PeerPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerService) DeepCopyInto(out *PeerService) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]PeerEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PeerPort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerService.
func (in *PeerService) DeepCopy() *PeerService {
	if in == nil {
		return nil
	}
	out := new(PeerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSync) DeepCopyInto(out *ServiceSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSync.
func (in *ServiceSync) DeepCopy() *ServiceSync {
	if in == nil {
		return nil
	}
	out := new(ServiceSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSyncList) DeepCopyInto(out *ServiceSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSyncList.
func (in *ServiceSyncList) DeepCopy() *ServiceSyncList {
	if in == nil {
		return nil
	}
	out := new(ServiceSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSyncSpec) DeepCopyInto(out *ServiceSyncSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.EndpointsPublishMax != nil {
		in, out := &in.EndpointsPublishMax, &out.EndpointsPublishMax
		*out = new(int32)
		**out = **in
	}
	if in.EndpointsConfigureMax != nil {
		in, out := &in.EndpointsConfigureMax, &out.EndpointsConfigureMax
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSyncSpec.
func (in *ServiceSyncSpec) DeepCopy() *ServiceSyncSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSyncStatus) DeepCopyInto(out *ServiceSyncStatus) {
	*out = *in
	if in.SelectedServices != nil {
		in, out := &in.SelectedServices, &out.SelectedServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PeerClusters != nil {
		in, out := &in.PeerClusters, &out.PeerClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PeerServices != nil {
		in, out := &in.PeerServices, &out.PeerServices
		*out = make(map[string][]PeerService, len(*in))
		for key, val := range *in {
			var outVal []PeerService
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]PeerService, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.PeerLastHeardFrom != nil {
		in, out := &in.PeerLastHeardFrom, &out.PeerLastHeardFrom
		*out = make(map[string]metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.LastPublishTime.DeepCopyInto(&out.LastPublishTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSyncStatus.
func (in *ServiceSyncStatus) DeepCopy() *ServiceSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceSyncStatus)
	in.DeepCopyInto(out)
	return out
}
