apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-robot

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mc-robot
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  - events
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - mc.q42.nl
  resources:
  - '*'
  - servicesyncs
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mc-robot
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
  
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mc-robot
subjects:
- kind: ServiceAccount
  name: mc-robot
roleRef:
  kind: Role
  name: mc-robot
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-robot-global
subjects:
- kind: ServiceAccount
  name: mc-robot
  namespace: default
roleRef:
  kind: ClusterRole
  name: mc-robot
  apiGroup: rbac.authorization.k8s.io