apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mc-robot
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  - events
  - nodes
  verbs:
  - '*'
- apiGroups:
  - mc.q42.nl
  resources:
  - '*'
  - servicesyncs
  verbs:
  - '*'
