kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mc-robot
subjects:
- kind: ServiceAccount
  name: mc-robot
roleRef:
  kind: Role
  name: mc-robot
  apiGroup: rbac.authorization.k8s.io
