name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      env:
        # Format: docker.pkg.github.com/:owner/:repo_name/:image_name
        # make build will append "/mc-robot"
        REGISTRY: docker.pkg.github.com/q42/mc-robot
      run: VERSION=$GITHUB_SHA make test build

    - name: Push
      env:
        REGISTRY: docker.pkg.github.com/q42/mc-robot
        REGISTRY_REPO: docker.pkg.github.com/q42/mc-robot/mc-robot
      shell: bash
      run: |
        # Login
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u $GITHUB_ACTOR --password-stdin $REGISTRY
        # Push (nb: ${var,,} is a bash trick to lowercase)
        export DESTINATION_SHA="docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mc-robot:$GITHUB_SHA"
        export DESTINATION_LATEST="docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mc-robot:latest"
        docker tag $REGISTRY_REPO:$GITHUB_SHA $DESTINATION_SHA
        docker tag $REGISTRY_REPO:$GITHUB_SHA $DESTINATION_LATEST
        docker push $DESTINATION_SHA
        docker push $DESTINATION_LATEST

    - uses: engineerd/setup-kind@v0.5.0
    - name: Debug
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
    - name: Install CRD and resources
      env:
        REGISTRY: docker.pkg.github.com/q42/mc-robot
      run: |
        # Get docker image access (see go.yml)
        ./kind-github.sh $GITHUB_ACTOR ${{ secrets.GITHUB_TOKEN }}

        # Install resources
        export DESTINATION_SHA="docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mc-robot:$GITHUB_SHA"
        cat deploy/* deploy/examples/* \
        sed "s/REPLACE_IMAGE/$DESTINATION_SHA/g" \
        kubectl apply --server-side -f -

    - name: Report
      run: curl -d "repo=github.com/q42/mc-robot" https://goreportcard.com/checks