name: "Create cluster using KinD"
on:
  workflow_run:
    workflows: ["Go"]
    branches: [master, feature/v1]
    types: 
      - completed

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Debug
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Install CRD and resources
        env:
          REGISTRY: docker.pkg.github.com/q42/mc-robot
        run: |
          # Get docker image access (see go.yml)
          ./kind-github.sh

          # Install resources
          export DESTINATION_SHA="docker.pkg.github.com/${GITHUB_REPOSITORY,,}/mc-robot:$GITHUB_SHA"
          cat deploy/* deploy/examples/* \
          sed "s/REPLACE_IMAGE/$DESTINATION_SHA/g" \
          kubectl apply --server-side -f -
